apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat8
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat8
    spec:
      containers:
        - name: tomcat8
          image: wsvblack/tomcat8-sample
          ports:
            - containerPort: 80