apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat8
spec:
  selector:
    app: tomcat8
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
