apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat8
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat8
    spec:
      containers:
        - name: tomcat8
          image: 
          ports:
            - containerPort: 80
